import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/components/ui/NavBar";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "PointXero",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-white/90 `}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
